name: Attendify_project
description: University Attendance System with Beacon Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2

  # HTTP Requests
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Bluetooth & Beacon Scanning
  flutter_blue_plus: ^1.31.0

  # Permissions
  permission_handler: ^11.1.0
  # iBeacon
  flutter_beacon: ^0.5.1
  #secure storage
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets (Logo, Images, etc.)
  assets:
    - assets/images/
    - assets/icons/

  # Fonts (Optional - Uncomment if you want custom fonts)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700