name: Attendify_project
description: University Attendance System with Beacon Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ðŸ‘‡ UPDATED VERSION TO FIX ERROR
  intl: ^0.20.2

  # Icon Generator
  flutter_launcher_icons: ^0.13.1

  # UI & Icons
  cupertino_icons: ^1.0.2

  # HTTP Requests
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0

  # For Students to SCAN QR codes (Modern & fast)
  mobile_scanner: ^5.0.0

  # For Location (Anti-Spoofing)
  geolocator: ^10.1.0


  # Bluetooth & Beacons
  flutter_beacon:
    path: C:/Users/ASH/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_beacon-0.5.1
  flutter_blue_plus: ^1.31.0        # Scanning
  flutter_ble_peripheral: ^2.0.0    # Broadcasting

  permission_handler: ^11.1.0

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  device_info_plus: ^10.0.0   # For Android version detection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# âœ… FLUTTER CONFIGURATION
flutter:
  uses-material-design: true

  # Assets (Logo, Images, etc.)
  assets:
    - assets/images/
    # If you access the icon directly in the app code, add this too:
    # - assets/icons/

# âœ… LAUNCHER ICONS CONFIGURATION
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
